version: "3"
services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - 40999:40999
    command: ["./main"]

  ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    ports:
      - 40998:40998
    command: ["./main"]